version: 0.2

phases:
  install:
    commands:
      - apt-get update -qq
      - apt-get install -qy --no-install-recommends python3 python3-venv git
  pre_build:
    commands:
      - mkdir -p /opt/ioiprint_venv
      - if [ -e /opt/ioiprint_venv.cache ]; then sha256sum -c /opt/ioiprint_venv.cache || rm -rf /opt/ioiprint_venv /opt/ioiprint_venv.cache; fi
      - if [ ! -e /opt/ioiprint_venv.cache ]; then mkdir -p /opt/ioiprint_venv; fi
      - chmod +x ./deploy/*.sh
      - git rev-parse HEAD > REVISION
  build:
    commands:
      - ./deploy/install-deps.sh
      - sha256sum requirements.txt > /opt/ioiprint_venv.cache
      - mkdir -p /out/
      - cp appspec.yml /out/
      - cp -av . /out/src
      - cp -av /opt/ioiprint_venv/ /out/venv
      - touch /out/venv/.built-on-codebuild

artifacts:
  files:
    - '**/*'
  base-directory: '/out'

cache:
  paths:
    - '/opt/ioiprint_venv.cache'
    - '/opt/ioiprint_venv/**/*'
