version: '3.1'

services:
  ioiprint:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      TZ: Asia/Tokyo
      IOIPRINT_CONFIG: >-
        {
          "contestant_max_pages": 10,
          "netadmin_url": "http://netadmin-api",
          "cups_server": "cups:631",
          "contestant_printer": "PDF",
          "default_printer": "PDF",
          "metrics_store_file": "/tmp/ioiprint.metrics.json"
        }

  cups:
    image: hanazuki/cups
    ports:
      - 6631:631
    environment:
      CUPS_ADMIN_USERNAME: admin
      CUPS_ADMIN_PASSWORD: ioi
    volumes:
      - ./output:/var/spool/cups-pdf/ANONYMOUS

  netadmin-api:
    build:
      context: stub-netadmin-api
