#!/bin/bash
set -eu

ARG_JOB=$1
ARG_OPTIONS=$5
ARG_FILENAME=${6:-}

PRINT_SERVER_ADDRESS=http://ioiprint:5000

time=$(date +%FT%T)

if [[ $ARG_FILENAME ]]; then
    filename=$ARG_FILENAME
else
    filename=$(mktemp -t "$time.XXXXXXXX")
    cat - >"$filename"
fi

if [[ $CONTENT_TYPE = application/vnd.cups-postscript ]]; then
    old_filename=$filename
    filename=$(mktemp -t "$time.XXXXXXXX")
    ps2pdf "$old_filename" "$filename"
fi

client=$(LANG=C perl -e 'print $1 if $ARGV[0] =~ /job-originating-host-name=(\S*)/' "$ARG_OPTIONS")

server_filename=$(curl -fsS --form "pdf=@${filename}" --form "type=contestant" "${PRINT_SERVER_ADDRESS}/upload")
echo "server filename: ${server_filename}" >&2

curl -fsS --data "filename=${server_filename}&ip=${client}&cups_job_id=${ARG_JOB}" "${PRINT_SERVER_ADDRESS}/contestant"
