#!/bin/bash
set -eu
trap 'exit 1' ERR  # CUPS_BACKEND_FAILED (ref. backend(7))

ARG_JOB=$1
ARG_OPTIONS=$5
ARG_FILENAME=${6:-}

IOIPRINT_URI=${DEVICE_URI/#ioiprint/http}

if [[ $CONTENT_TYPE != application/vnd.cups-pdf ]]; then
    echo "Content type not supported: $CONTENT_TYPE" >&2
    exit 5  # CUPS_BACKEND_CANCEL
fi

if [[ $ARG_FILENAME ]]; then
    filename=$ARG_FILENAME
else
    filename=$(mktemp -t "cups-job-${ARG_JOB}.XXXXXXXX.pdf")
    cat - >"$filename"
fi

client=$(LANG=C perl -e 'print $1 if $ARGV[0] =~ /job-originating-host-name=(\S*)/' "$ARG_OPTIONS")
if [[ -z $client ]]; then
    echo 'Client address not identified' >&2
    exit 5  # CUPS_BACKEND_CANCEL
fi

server_filename=$(curl -fsS --form "pdf=@${filename}" --form "type=contestant" "${IOIPRINT_URI}/upload")
echo "server filename: ${server_filename}" >&2

curl -fsS --data "filename=${server_filename}&ip=${client}&cups_job_id=${ARG_JOB}" "${IOIPRINT_URI}/contestant" >&2
